config/routes.rb
Rails.application.routes.draw do
  resources :order_services
  root to: "admin/orders#index"

  namespace :admin do
    resources :employees
    resources :categories
    resources :services
    resources :orders

    resources :order_services, except: [:index, :show]
    resources :employee_services, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
  has_many :order_services, dependent: :destroy
  has_many :orders, through: :order_services
  belongs_to :employee, optional: true

  validates :name, presence: true, uniqueness: {scope: :category_id}
  validates :price, numericality: { only_integer: false, greater_than_or_equal_to: 0 }
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::AdminController
  before_action :set_service, only: %i[ show edit update destroy ]

  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to admin_service_path(@service), notice: "Service was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to admin_service_path(@service), notice: "Service was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to admin_services_path, notice: "Service was successfully destroyed." }
    end
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:name, :price, :category_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= form_with(model: [:admin, service]) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

app/views/admin/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.category.name %></td>
        <td><%= service.price %></td>
        <td class="options"><%= link_to 'Show', admin_service_path(service) %></td>
        <td class="options"><%= link_to 'Edit', edit_admin_service_path(service) %></td>
        <td class="options"><%= link_to 'Destroy', admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

  </tbody>
</table>

<br>
<div class="options">
  <%= link_to 'New Service', new_admin_service_path %>
</div>

app/views/admin/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

app/views/admin/services/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Service</h1>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @service.category.name %> <%= link_to 'Show', admin_category_path(@service.category) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>


<div class="options">
  <%= link_to 'Edit', edit_admin_service_path(@service) %>
</div>