config/routes.rb
Rails.application.routes.draw do
  resources :order_services
  root to: "admin/orders#index"

  namespace :admin do
    resources :employees
    resources :categories
    resources :services
    resources :orders

    resources :order_services, except: [:index, :show]
    resources :employee_services, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :order_services
  has_many :services, through: :order_services

  validates :name, presence: true
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::AdminController
  before_action :set_employee, only: %i[ show edit update destroy ]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employee_path(@employee), notice: "Employee was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to admin_employee_path(@employee), notice: "Employee was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to admin_employees_path, notice: "Employee was successfully destroyed." }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admin/employees/_form.html.erb
<%= form_with(model: [:admin, employee]) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

app/views/admin/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td class="options"><%= link_to 'Show', admin_employee_path(employee) %></td>
        <td class="options"><%= link_to 'Edit', edit_admin_employee_path(employee) %></td>
        <td class="options"><%= link_to 'Destroy', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="options">
  <%= link_to 'New Employee', new_admin_employee_path %>
</div>

app/views/admin/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

app/views/admin/employees/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee</h1>

<strong>Name:</strong>
<%= @employee.name %>
<p>Now providing services:</p>
<% @employee.order_services.each do |order_service| %>
  <p>Order:<p>
  <%= order_service.order.id %>
  <p>Service:</p>
  <%= order_service.service.name %>
<% end %>


<div class="options">
  <%= link_to 'Edit', edit_admin_employee_path(@employee) %>
</div>