config/routes.rb
Rails.application.routes.draw do
  resources :order_services
  root to: "admin/orders#index"

  namespace :admin do
    resources :employees
    resources :categories
    resources :services
    resources :orders

    resources :order_services, except: [:index, :show]
    resources :employee_services, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_services, dependent: :destroy
  has_many :services, through: :order_services

  scope :filter_by_customer_name, -> (customer_name) {where customer_name: customer_name}
  scope :filter_by_created_at, -> (created_at) {where("DATE(created_at) = ?", created_at)}
  scope :filter_by_service_employee, -> (employee_id) {joins(:order_services).where(order_services: {employee_id: employee_id})}

  scope :filter_by_service_category, -> (category_id) {joins(:services).where( services: {category: category_id})}

  def total_price
    self.services.sum(:price)
  end

  validates :customer_name, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    if params[:commit] == "Filtered"
      @type_of_index_page = "Filtered"
      #params[:customer_name] || params[:created_at] || params[:employee] || params[:service] || params[:sort_by] || params[:type]
      @orders = Order.where(nil)
      @orders = @orders.filter_by_customer_name(params[:customer_name]) if params[:customer_name].present?

      @orders = @orders.filter_by_created_at(params[:created_at]) if params[:created_at].present?

      @orders = @orders.filter_by_service_employee(params[:employee_id]) if params[:employee_id].present?

      @orders = @orders.filter_by_service_category(params[:category_id]) if params[:category_id].present?

      @orders = @orders.order("created_at #{params[:type]}" ) if params[:sort_by] == "Date"

      @orders = @orders.order("customer_name #{params[:type]}" ) if params[:sort_by] == "Customer"

      @orders = @orders.left_joins(:services).group(:id).order("COUNT(services.id) #{params[:type]}" ) if params[:sort_by] == "Count services"


        respond_to do |format|
          format.html
          format.xlsx
        end
    else
      @orders = Order.all
    end
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_order_path(@order), notice: "Order was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_order_path(@order), notice: "Order was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_path, notice: "Order was successfully destroyed." }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:customer_name, :category)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order]) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Изменить заявку</h1>

<%= render 'form', order: @order %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>


<div class="filter">
  <%= form_with url: admin_orders_path, method: :get do |form| %>
  <h3>Orders filter</h3>
    <div class="field">
      <%= form.label :customer_name %>
      <%= form.text_field :customer_name %>
    </div>

    <div class="field">
      <%= form.label :created_at %>
      <%= form.date_field :created_at %>
    </div>

    <div class="field">
      <%= form.label :employee %>
      <%= form.collection_select :employee_id, Employee.all, :id, :name, prompt: "empty" %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "empty" %>
    </div>

    <h3>Orders sort</h3>
    <div class="field">
      <%= form.label :sort_by %>
      <%= form.select :sort_by, options_for_select(["Date", "Customer", "Count services"]) %>
    </div>

    <div class="field">
      <%= form.label :type %>
      <%= form.select :type, options_for_select(["DESC", "ASC"]) %>
    </div>

    <div class="actions">
      <%= form.submit "Filtered" %>
    </div>
  <% end %>
</div>


<% if @type_of_index_page == "Filtered" %>
  <%= link_to 'Download as .xlsx', admin_orders_path(format: :xlsx) %>
<% end %>
<h1>Orders</h1>
<hr>
  <% @orders.each do |order| %>
    <div class="order-body">
      <div class="label">Customer:</div>
      <div class="data">
        <%= order.customer_name %>
      </div>
      <div class="label">Date:</div>
      <div class="data">
        <%= order.created_at.strftime("%d-%m-%Y") %>
      </div>
      <% order.order_services.each do |order_service| %>
        <div class="order-service">

          <div class="label">Service:</div>
          <div class="data">
            <b><%= order_service.service.category.name %></b>
            <br>
            <%= order_service.service.name %>
            <div class="label-price">Price:</div>
            <div class="data">
              <%= order_service.service.price %>
            </div>
          </div>
          <div class="label">Executor:</div>
          <div class="data">
            <%= order_service.employee.name %>
          </div>
        </div>
      <% end %>
      <br>
      <div class="options">
        <%= link_to 'Show', admin_order_path(order) %>
        <%= link_to 'Edit', edit_admin_order_path(order) %>
        <%= link_to 'Delete', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <div class="label">Total price:</div>
    <div class="data">
      <%= order.total_price %>
    </div>
    <hr>
  <% end %>

<br>
<div class="options">
  <%= link_to 'New order', new_admin_order_path %>
</div>

app/views/admin/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

app/views/admin/orders/show.html.erb
<h1>Order №<%= @order.id %></h1>

<div class="order-body">
  <div class="label">Customer:</div>
  <div class="data">
    <%= @order.customer_name %>
  </div>
  <div class="label">Date:</div>
  <div class="data">
    <%= @order.created_at.strftime("%d-%m-%Y") %>
  </div>
  <% @order.order_services.each do |order_service| %>
    <div class="order-service">
      <div class="label">Service:</div>
      <div class="data">
        <b><%= order_service.service.category.name %></b>
        <br>
        <%= order_service.service.name %>
        <div class="label-price">Price:</div>
        <div class="data">
          <%= order_service.service.price %>
        </div>
      </div>
      <div class="label">Executor:</div>
      <div class="data">
        <%= order_service.employee.name %>
      </div>
      <div class="options">
        <%= link_to 'Edit service', edit_admin_order_service_path(order_service) %>
        <%= link_to 'Destroy', admin_order_service_path(order_service), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
  <div class="options">
    <%= link_to 'Add service', new_admin_order_service_path(order_id: @order.id) %>
    <%= link_to 'Edit', edit_admin_order_path(@order) %>
    <%= link_to 'Delete', admin_order_path(@order), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
<div class="label">Total price:</div>
<div class="data">
  <%= @order.total_price %>
</div>