config/routes.rb
Rails.application.routes.draw do
  resources :order_services
  root to: "admin/orders#index"

  namespace :admin do
    resources :employees
    resources :categories
    resources :services
    resources :orders

    resources :order_services, except: [:index, :show]
    resources :employee_services, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services, dependent: :destroy

  validates :name, uniqueness: true, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: "Category was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: "Category was successfully destroyed." }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name,)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class="options"><%= link_to 'Show', admin_category_path(category) %></td>
        <td class="options"><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td class="options"><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="options">
  <%= link_to 'New Category', new_admin_category_path %>
</div>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Category</h1>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Services:</strong>
  <table>
    <% @category.services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= link_to 'Show', admin_service_path(service) %></td>
        <td><%= link_to 'Edit', edit_admin_service_path(service) %></td>
        <td><%= link_to 'Destroy', admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</p>
<div class="options">
  <%= link_to 'Edit', edit_admin_category_path(@category) %>
</div>